### ISSUE TITLE
Move scripts for generating xml data stream files

### ISSUE THREAD

**Issue by dougiesquire** [COSIMA/om3-scripts#2]
The scripts used for generating the xml data stream files should be moved into this repo and removed from the configuration repos, e.g.:

- [generate_xml_datm.py](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_datm.py) 
- [generate_xml_drof.py](https://github.com/COSIMA/MOM6-CICE6/blob/1deg_jra55do_iaf/generate_xml_drof.py)

@ezhilsabareesh8, would you mind doing this since wrote the scripts. I'm happy to review.

**Comment by ezhilsabareesh8** [comment]
Thanks @dougiesquire. I have created a pull request to add xml files #4
