### ISSUE TITLE
Record git repo, hash and run command in generated XML

### ISSUE THREAD

**Issue by aekiss** [COSIMA/om3-scripts#5]
It would be good to include the [git repo, hash and run command like this](https://github.com/COSIMA/om3-scripts/blob/bbbbc3fe74de082135a7fdae6374dfb89339dd88/mesh_generation/generate_mesh.py#L407-L413) as an XML comment in the output from the two scripts in [`data_stream_xml_generation`](https://github.com/COSIMA/om3-scripts/tree/main/data_stream_xml_generation)

**Comment by dougiesquire** [comment]
@ezhilsabareesh8, the tools to get this metadata [have now](https://github.com/COSIMA/om3-scripts/pull/12) been moved into a `scripts_common.py` file in the base dir. Would you be able to use these to add the necessary provenance metadata in the `data_stream_xml_generation` scripts? You can find an example of how to use them in `generate_mesh.py`

**Comment by dougiesquire** [comment]
Note you can add comments to xml:
```
<!--
  This is a 
  multiline comment
-->
```
So you could add a comment with the metadata at the top of the file

**Comment by dougiesquire** [comment]
Closed by https://github.com/COSIMA/om3-scripts/pull/15
